audit_header: false
title: Madison Real Estate Video Blog with Jo Ferraro
description: Our mission at Ferraro Real Estate Team is to be your best resource for Madison real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Ferraro Real Estate Team, your professional Madison Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jo Ferraro
  title:
  license_number:
  about_markdown: |
    Jo Ferraro has been consistently recognized as a top real estate agent in South Central Wisconsin since 1999. In fact, she has distinguished herself within the top 1% of all real estate agents in the nation. She combines her extensive market knowledge, tough negotiating skills and award-winning service with the understanding that you're not just buying a house but you're buying a home.

    Outside of real estate, Jo spends her time making memories with her husband and 5 amazing and beautiful children. Together, they enjoy hiking, boating, walking through the Madison Farmer's Market and UW-Arboretum as well as trying new restaurants.
  brand: Ferraro Real Estate Team
  brokerage: eXp Realty
  market: Madison
  address: 4810 Larson Beach Rd, McFarland, WI 53558
  phone: 608-445-2287
  phone_type:
  phone2:
  phone2_type:
  email: Requests@SoldinMadison.com
  url: http://www.soldinmadison.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.allhomesinmadison.com/homevalue/joferraroteam
  second_CTA_text: Home Search
  second_CTA_URL: https://www.allhomesinmadison.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Madison Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.allhomesinmadison.com/homevalue/joferraroteam

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Madison Home?"
    CTA_text2: "Search the entire MLS for your Madison home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.allhomesinmadison.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheFerraroRealEstateTeam/
  linkedin_url: http://www.linkedin.com/in/joferraro
  youtube_url: https://www.youtube.com/channel/UCfHoDneq6oZ7qb2TWF27_5A
  twitter_url: https://twitter.com/Sold_in_Madison
  instagram_url:
  pinterest_url: http://www.pinterest.com/soldinmadison/
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Madison Real Estate Podcast with Jo Ferraro'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Madison Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Ferraro Real Estate Team - your professional Madison Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Madison, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jo Ferraro'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Madison Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#055084'
  theme_color: '#f5821f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#055084'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
